# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
    inputs:
    targetType: 'inline'
      script: |
        # Step 3. Form the header and add the Authorization attribute to it
        $headers = @{ Authorization = "Basic Z2FuZXNoMDEyOmdhbmVzaDAxOQ==" }
        
        #URI
        $url = "http://10.192.65.37/LoadTest/rest/authentication-point/authenticate"
         
        # Step 4. Make the GET request
        $responseData = Invoke-WebRequest -Uri $url -Method Get -Headers $headers -UseBasicParsing
         
        return $responseData

  
